### ISSUE TITLE
It's not work after install

### ISSUE THREAD

**Issue by sabakugaara** [filipekiss/nestjs-cli-completion#1]
I've tried two installation methods: 
1. step by step, follow your readme
2. just cp `_nest` file to `~.zfunc` directory. And my `.zshrc` had configured this: 
    `fpath=( ~/.zfunc "${fpath[@]}" )` 

they all not work.  
Please help me thanks!

**Comment by qtlwc** [comment]
@sabakugaara Try this, it works for me:[^1]
```bash
fpath=(${fpath} ${HOME}/.completion/nestjs)
autoload -U ${HOME}/.completion/nestjs/_nest
compdef _nest nest
```
![screenshot](https://github.com/filipekiss/nestjs-cli-completion/assets/128229048/3cbd2d58-cf2f-4b9a-ba08-aab3fc096024)

[^1]: https://unix.stackexchange.com/a/526429

**Comment by tukpedro** [comment]
Hey @sabakugaara, try to add at the top of .zshrc file the following lines:

```
fpath=(${fpath} ${HOME}/.completion/nestjs)
autoload -U ${HOME}/.completion/nestjs/_nest
```

It worked for me.
